"""Vocabulário controlado — fonte: 02_DICIONARIO_DE_DADOS_P05_R01.csv e
03_VOCABULARIO_CONTROLADO_DE_STATUS_P05_R01.csv.

Cada enum é uma enumeração fechada. Valor fora da lista é rejeitado pelo
próprio Python (ValueError na construção).
"""

from enum import Enum


class ClaimType(str, Enum):
    FATUAL = "FATUAL"
    INTERPRETATIVA = "INTERPRETATIVA"
    CITACAO = "CITACAO"
    METODOLOGICA = "METODOLOGICA"
    NORMATIVA = "NORMATIVA"
    OUTRA_CONTROLADA = "OUTRA_CONTROLADA"


class SourceType(str, Enum):
    DOCUMENTO = "DOCUMENTO"
    BASE_DE_DADOS = "BASE_DE_DADOS"
    IMAGEM = "IMAGEM"
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"
    WEB = "WEB"
    REGISTRO_INTERNO = "REGISTRO_INTERNO"
    OUTRO_CONTROLADO = "OUTRO_CONTROLADO"


class LocationType(str, Enum):
    PAGINA = "PAGINA"
    FOLIO = "FOLIO"
    SECAO = "SECAO"
    TIMECODE = "TIMECODE"
    CELULA = "CELULA"
    REGISTRO = "REGISTRO"
    URL = "URL"
    ARQUIVO = "ARQUIVO"
    NAO_APLICAVEL = "NAO_APLICAVEL"
    NAO_CONFIRMADO = "NAO_CONFIRMADO"


class EvidenceLevel(str, Enum):
    A_INTERNA_FORNECIDA = "A_INTERNA_FORNECIDA"
    B_MATERIAL_ANEXADA = "B_MATERIAL_ANEXADA"
    C_FERRAMENTA_RASTREAVEL = "C_FERRAMENTA_RASTREAVEL"
    D_AUSENTE = "D_AUSENTE"


class AccessState(str, Enum):
    NAO_LOCALIZADA = "NAO_LOCALIZADA"
    LOCALIZADA = "LOCALIZADA"
    ACESSIVEL = "ACESSIVEL"
    ACESSADA = "ACESSADA"


class ReadingState(str, Enum):
    LEITURA_NAO_REALIZADA = "LEITURA_NAO_REALIZADA"
    LEITURA_INDIRETA = "LEITURA_INDIRETA"
    LIDA_PARCIALMENTE = "LIDA_PARCIALMENTE"
    LIDA_INTEGRALMENTE = "LIDA_INTEGRALMENTE"


class ValidationState(str, Enum):
    NAO_VERIFICADA = "NAO_VERIFICADA"
    PAGINA_NAO_CONFIRMADA = "PAGINA_NAO_CONFIRMADA"
    PAGINA_CONFIRMADA = "PAGINA_CONFIRMADA"
    VALIDACAO_PENDENTE = "VALIDACAO_PENDENTE"
    VALIDADA = "VALIDADA"
    INVALIDADA_POSTERIORMENTE = "INVALIDADA_POSTERIORMENTE"


class Sufficiency(str, Enum):
    NAO_AVALIADA = "NAO_AVALIADA"
    EVIDENCIA_AUSENTE = "EVIDENCIA_AUSENTE"
    EVIDENCIA_INSUFICIENTE = "EVIDENCIA_INSUFICIENTE"
    EVIDENCIA_PARCIALMENTE_SUFICIENTE = "EVIDENCIA_PARCIALMENTE_SUFICIENTE"
    EVIDENCIA_SUFICIENTE = "EVIDENCIA_SUFICIENTE"
    CONFLITANTE = "CONFLITANTE"


class Confidence(str, Enum):
    NAO_AVALIADA = "NAO_AVALIADA"
    BAIXA = "BAIXA"
    MEDIA = "MEDIA"
    ALTA = "ALTA"


class UsageStatus(str, Enum):
    NAO_USAR = "NAO_USAR"
    USO_CONDICIONAL = "USO_CONDICIONAL"
    USO_LIBERADO = "USO_LIBERADO"
    ABSTENCAO = "ABSTENCAO"


class Reversibility(str, Enum):
    REVERSIVEL_COM_NOVA_EVIDENCIA = "REVERSIVEL_COM_NOVA_EVIDENCIA"
    REVERSIVEL_POR_CORRECAO = "REVERSIVEL_POR_CORRECAO"
    NAO_APLICAVEL = "NAO_APLICAVEL"


# Valores controlados aplicáveis a campos condicionais quando o dado real
# é desconhecido (arquivo 01, seção 4). Não são um enum de campo específico;
# são reutilizados por vários campos de texto livre condicionais.
NAO_APLICAVEL = "NAO_APLICAVEL"
NAO_CONFIRMADO = "NAO_CONFIRMADO"
DESCONHECIDO_CONTROLADO = "DESCONHECIDO_CONTROLADO"
RESUMO_DECLARADO = "RESUMO_DECLARADO"
NAO_DISPONIVEL = "NAO_DISPONIVEL"
